acrn-config: P2SB Bridge Passthrough and expose GPIO Chassis Interrupt to the Safety VM as INTx
projectacrn/acrn-hypervisor pull request #5222
Opened 2020-08-25 02:18 UTC by donsheng

-  Support for direct assignment of P2SB bridge to one pre-launched safety VM for EHL
 - Expose GPIO chassis interrupts as INTx to the safety VM for EHL
 - Fix misspelled function name

2020-08-25 02:25 UTC, HuiHuangShi commented
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

2020-08-25 02:51 UTC, jsun26intel commented on misc/acrn-config/library/board_cfg_lib.py
> +P2SB_PASSTHRU_SCENARIO = ('hybrid', 'hybrid_rt')
I prefer to use vm0_pre_launch like tpm_passthru to instead specific scenario because customer might have their own scenario name.

2020-08-25 02:53 UTC, jsun26intel commented on misc/acrn-config/board_config/board_info_h.py
> +        if 'INTC1020:' in line:
INTC1020 is specific for ehl right? better add condition here that board is ehl_crb_b

2020-08-25 02:55 UTC, jsun26intel commented on misc/acrn-config/board_config/board_info_h.py
> +    common.print_red('"INTC1020:" is not found in board file %s!\n' % common.BOARD_INFO_FILE, err=True)
I prefer to use "p2sb device" instead of "INTC1020".

2020-08-25 02:58 UTC, jsun26intel commented on misc/acrn-config/library/scenario_cfg_lib.py
> +            ERR_LIST["vm:id=0,p2sb"] = "p2sb can only be enabled for EHL hybrid/hybrid-rt"
no need to mention scenaio name. It should work on a pre-launched VM0.

2020-08-25 03:04 UTC, jsun26intel commented on misc/acrn-config/scenario_config/vm_configurations_c.py
> +        print("\t\t\t.base_gpa = P2SB_BAR_ADDR,", file=config)
for base_gpa, it should be a calculated address, so better not use MACRO here. please refer implementation of TPM (but do not use prefix of VM0_xxx, which should be fixed when general mmio passthru framework is ready).

2020-08-25 03:11 UTC, jsun26intel commented on misc/acrn-config/library/scenario_cfg_lib.py
> +    if scenario != "hybrid" and scenario != "hybrid_rt":
can't work on a pre-launched VM0 of other scenarios?

2020-08-25 03:12 UTC, jsun26intel requested changes
Do you sync with Zheng, Shuang on UI part?

2020-08-25 03:20 UTC, jsun26intel commented on misc/acrn-config/library/scenario_cfg_lib.py
> +    if scenario != "hybrid" and scenario != "hybrid_rt":
per subject "expose GPIO Chassis Interrupt to the Safety VM as INTx", if this is for safety VM only, then we need to add condition that the VM0 is a safety VM, and "hybrid_rt" does not satisfy this condition.

2020-08-25 05:58 UTC, HuiHuangShi commented
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

2020-08-25 07:03 UTC, HuiHuangShi commented
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

2020-08-26 04:02 UTC, closed without merging

2020-08-26 04:02 UTC, donsheng commented
Close it so that I can pr another patch