dm: refine ivshmem usage interface
projectacrn/acrn-hypervisor pull request #5305
Opened 2020-09-11 01:09 UTC by liuyuan-GitHub

Change shared memory name prefix from sos to dm
Change shared memory size unit from byte to megabyte

Tracked-On: #4853

Signed-off-by: Yuan Liu <yuan1.liu@intel.com>
Acked-by: Wang, Yu1 <yu1.wang@intel.com>

2020-09-11 01:13 UTC, ywan170 approved these changes

2020-09-11 01:17 UTC, HuiHuangShi commented
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

2020-09-11 13:22 UTC, HuiHuangShi commented
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

2020-09-11 14:50 UTC, gvancuts approved these changes
Thanks!

2020-09-11 22:32 UTC, dbkinder requested changes

2020-09-11 22:32 UTC, dbkinder commented on devicemodel/hw/pci/ivshmem.c
> +		pr_warn("Invalid shared memory size %u, the size range is [2MB,512MB], the unit is megabyte and the value must be a power of 2\n",
The value of ``size`` was converted to megabytes on line 275, so the value shown in this error message is no longer the value specified by the user.  Change the value in this error message to be divided by 0x100000.

2020-09-14 01:01 UTC, HuiHuangShi commented
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

2020-09-14 21:23 UTC, dbkinder approved these changes
Thanks!

2020-09-15 01:41 UTC, merged