doc: Add note about the maximum number of regions for hv-land
projectacrn/acrn-hypervisor pull request #5335
Opened 2020-09-17 03:46 UTC by liuyuan-GitHub

The maximum number of ivshmem shared memory regions cannot exceed 8

Signed-off-by: Yuan Liu <yuan1.liu@intel.com>

2020-09-17 03:54 UTC, HuiHuangShi commented
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

2020-09-17 13:43 UTC, gvancuts approved these changes
The tech content is obviously correct, I'll let @dbkinder check for any changes to be made to the language. Thanks!

2020-09-17 22:34 UTC, dbkinder requested changes

2020-09-18 01:05 UTC, liuyuan-GitHub commented on doc/tutorials/enable_ivshmem.rst
> +   .. note:: If you need to define multiple ``IVSHMEM_REGION`` fields, the maximum number of ``IVSHMEM_REGION`` fields cannot exceed 8.
No, the limitation only works for hv-land

2020-09-18 01:14 UTC, HuiHuangShi commented
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

2020-09-18 17:07 UTC, dbkinder approved these changes

2020-09-18 17:07 UTC, merged