doc: update ivshmem feature HLD
projectacrn/acrn-hypervisor pull request #5486
Opened 2020-11-08 03:49 UTC by yonghuah

With ivshmem doorbell feature enabled, HDL of it shall be updated.

Signed-off-by: Yonghua Huang <yonghua.huang@intel.com>

2020-11-08 03:57 UTC, HuiHuangShi commented
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

2020-11-08 07:10 UTC, HuiHuangShi commented
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

2020-11-08 21:58 UTC, dbkinder requested changes
Thanks for the doc update.

2020-11-08 21:58 UTC, dbkinder commented on doc/developer-guides/hld/ivshmem-hld.rst
> +   doesn't support a notification mechanism for dm-land ivshmem devices.
I'd suggest rewriting this as:
```
A daemon for inter-VM notification capability that will work with **ivshmem
dm**.  This is currently not implemented for **dm-land** ivshmem devices.

For **hv-land** ivhsmem devices, a notification mechanism (doorbell) is enabled.
The VM triggers the notification by writing the target peer ID (VM ID) and 
vector index to the doorbell register.  The Hypervisor finds the target
ivshmem device by this peer ID and injects a virtual interrupt to the target VM. 
```

2020-11-08 21:58 UTC, dbkinder commented on doc/developer-guides/hld/ivshmem-hld.rst
> +three Base Address Registers (BARs): BAR0 is used for emulating interrupt
Suggested rewrite:
```
The ``ivshmem`` device is a virtual standard PCI device consisting of
three Base Address Registers (BARs): 

* BAR0 is used for emulating interrupt related registers, 
* BAR1 is used for emulating MSIX entry table, and
* BAR2 is used for exposing a shared memory region.

The ``ivshmem`` device supports no extra capabilities.
```

2020-11-09 07:45 UTC, yonghuah commented
@dbkinder  have updated this PR, please review ,thanks.

2020-11-09 07:53 UTC, HuiHuangShi commented
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

2020-11-09 08:14 UTC, gvancuts reviewed
The text looks good. I'm not sure I fully understand the diagram at the beginning of the document as it shows an `ivshmem server` running in the Service VM that interacts only with acrn-dm` instances. Are there details missing to describe this new feature?

2020-11-09 09:27 UTC, yonghuah commented
@gvancuts  thanks for comments,  I refined  some desc. pls review, thanks.

2020-11-09 09:31 UTC, gvancuts commented
Thanks @yonghuah . If you have the ability to add a box showing this `ivshmem server` module in the hypervisor box, that would be even better, but not a blocker for this PR. Thanks! 👍

2020-11-09 09:33 UTC, HuiHuangShi commented
No new violations to the coding guideline detected.<br>No New Name Conflict<br><br>No New Function Declaration/Definition Mismatch<br>

2020-11-09 15:12 UTC, dbkinder approved these changes
Thanks for fixing the other areas in the doc that talked about this.  LGTM now.

2020-11-11 00:47 UTC, merged