acrn-config: Update generated configuration source code
projectacrn/acrn-hypervisor pull request #5678
Opened 2021-01-29 08:25 UTC by NanlinXie

1. Reorg generated configuration source code structure
2. Upstream generated configuration source code based on generic board infomation

Tracked-On: #5644
Signed-off-by: Xie, nanlin <nanlin.xie@intel.com>

2021-01-29 14:26 UTC, gvancuts requested changes
There are many files with copyright information indicating year 2020 (or older). These should be updated to 2021.

You have a number of `*.d` and object (`*.o`) files included in these commits (e.g. `misc/config_tools/data/generic_board/generic_code/hybrid/pci_dev.o`), can you remove them?

2021-01-29 14:26 UTC, gvancuts commented on misc/config_tools/data/generic_board/generic_code/hybrid/pci_dev.d
> +/home/nlxie/samba/branches/github/nlxie_github/acrn-hypervisor-1/build/hypervisor/configs/scenarios/hybrid/pci_dev.o: \
It looks like this file shouldn't be here.

2021-01-29 14:26 UTC, gvancuts commented on misc/config_tools/data/generic_board/generic_code/hybrid/vm_configurations.d
> +/home/nlxie/samba/branches/github/nlxie_github/acrn-hypervisor-1/build/hypervisor/configs/scenarios/hybrid/vm_configurations.o: \
Please remove this file.

2021-01-30 06:12 UTC, HuiHuangShi commented
No new violations to the coding guideline detected.<br>No New Name Conflict<br>No New Function Declaration/Definition Mismatch

2021-02-02 01:11 UTC, wenlingz commented
@NanlinXie  please rebase your code, thanks

2021-02-02 08:45 UTC, NanlinXie commented on misc/config_tools/data/generic_board/generic_code/hybrid/vm_configurations.d
> +/home/nlxie/samba/branches/github/nlxie_github/acrn-hypervisor-1/build/hypervisor/configs/scenarios/hybrid/vm_configurations.o: \
Done

2021-02-02 08:45 UTC, terryzouhao approved these changes

2021-02-02 08:53 UTC, merged