doc: update another few mis-handled titles
projectacrn/acrn-hypervisor pull request #5758
Opened 2021-02-23 12:09 UTC by gvancuts

After grand update of all titles to use title-case, we found some more
that needed a manual tweak.

Signed-off-by: Geoffroy Van Cutsem <geoffroy.vancutsem@intel.com>

2021-02-23 19:49 UTC, dbkinder requested changes
Thanks Geoffroy. Most changes are fine, some could use an edit...

2021-02-24 09:23 UTC, gvancuts commented on doc/api/GVT-g_api.rst
> +GVT-g ``intel_gvt_ops`` Interface
Makes sense

2021-02-24 09:24 UTC, gvancuts commented on doc/developer-guides/hld/hv-partitionmode.rst
> +Guests w/o LAPIC Passthrough
I agree

2021-02-24 09:24 UTC, gvancuts commented
I have updated my PR and force-pushed my changes. PTAL

2021-02-24 19:35 UTC, dbkinder approved these changes
LGTM, thanks!

2021-02-24 21:02 UTC, fitchbe commented
Just FYI (I can fix this in a new PR): The title-case Python module used the APA style rules, so any word (even a preposition) that's four letters or longer got capitalized. Unless we decide to apply a _different_ style (e.g., Chicago Manual of Style or others that specify _five_ letters or longer), we should just follow the APA guidelines to be consistent and capitalize both _with_ and _without_ in titles.

2021-02-24 21:06 UTC, gvancuts commented
> 
> 
> Just FYI (I can fix this in a new PR): The title-case Python module used the APA style rules, so any word (even a preposition) that's four letters or longer got capitalized. Unless we decide to apply a _different_ style (e.g., Chicago Manual of Style or others that specify _five_ letters or longer), we should just follow the APA guidelines to be consistent and capitalize both _with_ and _without_ in titles.

I can do this.

Should we also update these other titles then?
* `vmexit Analysis for ACRN RT Performance` (**for**)
* `Perf/PMU Tools in Performance Analysis` (**in**)
There are some others.

2021-02-24 22:58 UTC, fitchbe commented
No, the prepositions _under_ four letters in length should stay lowercase.

2021-02-24 23:03 UTC, gvancuts commented
> No, the prepositions _under_ four letters in length should stay lowercase.

Oh yes, I had spaced out on that piece.... I'll update the PR. Thanks!

2021-02-24 23:10 UTC, gvancuts commented
> I'll update the PR.

Done, PTAL

2021-02-24 23:14 UTC, fitchbe approved these changes

2021-02-24 23:14 UTC, merged