doc: make the "logical partitioning" description more generic
projectacrn/acrn-hypervisor pull request #5906
Opened 2021-04-06 21:59 UTC by gvancuts

Make the description of the "Logial Partitioning" scenario more
generic than what is shown on the figure. This also helps as the
current examples of that scenario in the code base do not use
Safety or RTVM at the moment (as shown on the picture).

Tracked-On: #5903
Signed-off-by: Geoffroy Van Cutsem <geoffroy.vancutsem@intel.com>

2021-04-07 00:14 UTC, dbkinder requested changes

2021-04-07 00:14 UTC, dbkinder commented on doc/introduction/index.rst
> +partitioning: both User VMs are independant and isolated, they do not share
independent (with an 'e')

2021-04-07 00:37 UTC, fitchbe approved these changes

2021-04-07 00:37 UTC, fitchbe commented on doc/introduction/index.rst
> +The User VMs can be Real-Time VMs (RTVMs), Safety VMs or standard User VMs.
Serial comma after "resources", and one after "Safety VMs".

2021-04-07 08:31 UTC, gvancuts commented
Addressed the comments and force-pushed the changes. PTAL.

2021-04-08 22:05 UTC, dbkinder approved these changes
LGTM, thanks!

2021-04-13 14:22 UTC, NanlinXie commented
Currently it's impossible to have two safety VM, we may need fix the picture firstly and maybe we could add a clause at the end highlighting the constraint on the number of safety VMs / RTVMs that can coexist in one scenario.

2021-04-13 21:22 UTC, dbkinder commented
@gvancuts Do you want to address @NanlinXie comment now, or in another PR?

2021-04-14 07:39 UTC, gvancuts commented
> @gvancuts Do you want to address @NanlinXie comment now, or in another PR?

I'll address it in this PR.

@NanlinXie , is this a hard limitation that's here to stay?

2021-04-16 02:09 UTC, junjiemao1 commented
@gvancuts Though not a hard limitation in ACRN, having at most one safety VM is typical and highly recommended in safety-related system architecture and this is what we are exploring in safety uses. I would recommend to fix on this before we get a clear idea on the implication of having multiple safety VMs in a single scenario.

2021-04-19 22:04 UTC, gvancuts commented
I have updated the picture in this latest version of the Pull Request. Can you all please take a look?

2021-04-19 22:57 UTC, fitchbe commented
The new picture looks good to me.

2021-04-20 00:12 UTC, dbkinder commented
OK to verify

2021-04-20 20:28 UTC, merged