doc: update the ACRN on QEMU tutorial to v2.4
projectacrn/acrn-hypervisor pull request #5937
Opened 2021-04-15 21:44 UTC by gvancuts

Update the "Running ACRN on QEMU" tutorial to be based on ACRN
v2.4 and Ubuntu 20.04.

Signed-off-by: Geoffroy Van Cutsem <geoffroy.vancutsem@intel.com>

2021-04-20 00:08 UTC, dbkinder requested changes
thanks @gvancuts

2021-04-20 00:08 UTC, dbkinder commented on doc/tutorials/acrn_on_qemu.rst
> +   via SSH. The IP address can be retrieved using via the ``virsh`` command as shown below.
```suggestion
   via SSH. The IP address can be retrieved using the ``virsh`` command as shown below.
```

2021-04-20 00:08 UTC, dbkinder commented on doc/tutorials/acrn_on_qemu.rst
> +#. Once logged into the Service VM, enable the serial console as, once ACRN is enabled,
```suggestion
#. Once logged into the Service VM, enable the serial console. Once ACRN is enabled,
```

2021-04-20 00:08 UTC, dbkinder commented on doc/tutorials/acrn_on_qemu.rst
> +      When shutting down the Service VM, make sure to cleanly destroy it
```suggestion
      When shutting down the Service VM, make sure to cleanly destroy it with these commands,
```

2021-04-20 00:08 UTC, dbkinder commented on doc/tutorials/acrn_on_qemu.rst
> +#. Copy the User VM kernel to your home folder, we will use it to launch the User VM (L2 guest)
```suggestion
#. Copy the User VM kernel to your home folder. We will use it to launch the User VM (L2 guest)
```

2021-04-20 13:27 UTC, gvancuts commented
Thanks @dbkinder , I have merged all the changes you proposed.

2021-04-20 20:33 UTC, dbkinder commented
ok to verify

2021-04-20 20:48 UTC, dbkinder commented
@NanlinXie @wenlingz Would you figure out why this doc-change only PR is failing build tests...

2021-04-21 02:11 UTC, wenlingz commented
> @NanlinXie @wenlingz Would you figure out why this doc-change only PR is failing build tests...

done

2021-04-22 05:13 UTC, wenlingz commented
ok to verify

2021-05-20 21:23 UTC, dbkinder approved these changes
LGTM, but do we now want to update this for v2.5?

2021-05-20 21:24 UTC, dbkinder commented
@gvancuts is this ready to not be a "draft" so we can merge and publish?  Do you want to update to work with v2.5 since that's the upcoming release?

2021-05-27 09:10 UTC, gvancuts commented
> @gvancuts is this ready to not be a "draft" so we can merge and publish? Do you want to update to work with v2.5 since that's the upcoming release?

I'm still keeping this as a draft because I am not able to run ACRN on QEMU using this tutorial. @fuzhongl is able to make it work but we do not understand yet what the difference is between his environment and mine that makes it work for him but fail for me.

Once that's figured out, I'll mark it as "Ready for review" and hopefully we can merge this. I may update this to v2.5 too if I have time... we'll see.

2021-05-27 09:40 UTC, gvancuts commented
I cannot test on v2.5 for now because of #6102 (compilation failure).

2021-05-31 15:29 UTC, gvancuts commented
It's now running on my side so moving this from draft to "ready for review"!

2021-06-01 05:13 UTC, dbkinder commented
> Thanks @dbkinder , I have merged all the changes you proposed.

It doesn't look like the proposed changes were made?

2021-06-01 05:15 UTC, dbkinder requested changes
@gvancuts it doesn't look like the suggested edits were actually made?

2021-06-01 12:02 UTC, fuzhongl commented
> It's now running on my side so moving this from draft to "ready for review"!

@gvancuts 
Sometimes ACRN will assert with following error log:
`Assertion failed in file arch/x86/vtd.c,line 256 : fatal error`
Dev team is trying to narrow down and root cause it.

This issue can be workaround with below command in native:
`sudo systemctl set-default multi-user.target`

Could you please help to add this information in this PR before the final fix?
Thanks!

2021-06-01 13:03 UTC, gvancuts commented
> @gvancuts it doesn't look like the suggested edits were actually made?

My bad, not sure what I did (or did not do as the case may be). I have now committed all these changes.

2021-06-01 13:07 UTC, gvancuts commented
> @gvancuts
> Sometimes ACRN will assert with following error log:
> `Assertion failed in file arch/x86/vtd.c,line 256 : fatal error`

I have seen this too, on rather few occasions thankfully, but it would be good to root-cause it!

> Dev team is trying to narrow down and root cause it.

Great - thanks!
 
> This issue can be workaround with below command in native:
> `sudo systemctl set-default multi-user.target`

Hmm... I believe that error is happening when the kernel is booting up, how confident are you that it's something later when the user-space is coming up that's causing this?
 
> Could you please help to add this information in this PR before the final fix?

Are we confident this is really a workaround?

2021-06-02 00:26 UTC, fuzhongl commented
> > @gvancuts
> > Sometimes ACRN will assert with following error log:
> > `Assertion failed in file arch/x86/vtd.c,line 256 : fatal error`
> 
> I have seen this too, on rather few occasions thankfully, but it would be good to root-cause it!
> 
> > Dev team is trying to narrow down and root cause it.
> 
> Great - thanks!
> 
> > This issue can be workaround with below command in native:
> > `sudo systemctl set-default multi-user.target`
> 
> Hmm... I believe that error is happening when the kernel is booting up, how confident are you that it's something later when the user-space is coming up that's causing this?
> 
> > Could you please help to add this information in this PR before the final fix?
> 
> Are we confident this is really a workaround?

@gvancuts Developer think this issue is related with GPU who is using DMA at that moment.
With `sudo systemctl set-default multi-user.target` , the issue can't be reproduced for more than tens of qemu `destroy` and `start`. Anyway, Dev team will root cause and fix it later.

2021-06-02 09:28 UTC, gvancuts commented
@fuzhongl @dbkinder PTAL

2021-06-02 22:45 UTC, fuzhongl commented
> @fuzhongl @dbkinder PTAL

@gvancuts Thanks for update!
There is another issue for v2.4 as mentioned in 5938:
```
detect_hardware_support, physical-address width (40) over maximum physical-address width (39)
[0us][cpu=0][(null)][sev=1][seq=2]:PANIC: init_pcpu_pre line: 132
[0us][cpu=0][(null)][sev=1][seq=3]:hardware not support!
```

Need following change:
```
diff --git a/hypervisor/include/arch/x86/page.h b/hypervisor/include/arch/x86/page.h
index 1094fa30d..e7c042903 100644
--- a/hypervisor/include/arch/x86/page.h
+++ b/hypervisor/include/arch/x86/page.h
@@ -14,7 +14,7 @@
 #define PAGE_SIZE      (1U << PAGE_SHIFT)
 #define PAGE_MASK      0xFFFFFFFFFFFFF000UL

-#define MAXIMUM_PA_WIDTH       39U     /* maximum physical-address width */
+#define MAXIMUM_PA_WIDTH       40U     /* maximum physical-address width */

 /* size of the low MMIO address space: 2GB */
 #define PLATFORM_LO_MMIO_SIZE  0x80000000UL
```
Will merge it to 2.4 branch or highlight this in this PR?
@gvancuts What's your prefer?

2021-06-03 10:06 UTC, gvancuts commented
> I cannot test on v2.5 for now because of #6102 (compilation failure).

#6102 has been resolved and the fix backported to the `release_2.5` branch. As a result of this, I have updated the tutorial to be based on ACRN v2.5.

**Important note**: this tutorial uses the `v2.5` tag for **both** the `acrn-hypervisor` and `acrn-kernel` repositories. These tags do not exist yet and my own local testing was based on the `release_2.5` branches.

2021-06-03 11:26 UTC, gvancuts commented
> Will merge it to 2.4 branch or highlight this in this PR?
> @gvancuts What's your prefer?

I have updated the PR to use v2.5 as the new baseline now that the blocking issue has been resolved. I don't think we should merge this to our 2.4 release. We _could_ add a note to show the patch in case someone wants to use the v2.4 release but I think at this stage it's actually better to redirect everyone to v2.5 so I wouldn't even include that note.

2021-06-04 02:21 UTC, NanlinXie approved these changes

2021-06-09 15:37 UTC, dbkinder approved these changes
LGTM, thanks!

2021-06-09 15:37 UTC, merged