hv: timer modularization
projectacrn/acrn-hypervisor pull request #6002
Opened 2021-05-12 05:14 UTC by ylian16

This patch set provides modularization for timer. Tracked on #5920.

2021-05-12 08:25 UTC, dongyaozu approved these changes

2021-05-12 16:27 UTC, fitchbe approved these changes

2021-05-13 01:15 UTC, wenlingz commented
@ylian16 please rebase your code, thanks

2021-05-13 07:49 UTC, wenlingz commented
@ylian16 please check your code, fail to launch waag(waag hang) in TGL hybrid-rt and WHL industry and EHL hybrid-rt. 
please refer log:

root@1921681219sos-dom0:~/waag# cd /home/root/waag && bash launch_uos_id1.sh
tap device existed, reuse tap_WaaG
logger: name=console, level=4
logger: name=kmsg, level=3
logger: name=disk, level=5
SW_LOAD: get ovmf path /usr/share/acrn/bios/OVMF.fd, size 0x200000
vm_create: post_vm_id1
VHM api version 1.0
vm_setup_memory: size=0x100000000
open hugetlbfs file /run/hugepage/acrn/huge_lv1/post_vm_id1/D279543825D611E8864ECB7A18B34643
open hugetlbfs file /run/hugepage/acrn/huge_lv2/post_vm_id1/D279543825D611E8864ECB7A18B34643
level 0 free/need pages:1/1 page size:0x200000
level 1 free/need pages:11/4 page size:0x40000000

try to setup hugepage with:
	level 0 - lowmem 0x0, biosmem 0x200000, highmem 0x0
	level 1 - lowmem 0x80000000, biosmem 0x0, highmem 0x80000000
total_size 0x1c0000000

mmap ptr 0x0x7f1b85ea8000 -> baseaddr 0x0x7f1bc0000000
mmap 0x80000000@0x7f1bc0000000
touch 2 pages with pagesz 0x40000000
mmap 0x80000000@0x7f1cc0000000
touch 2 pages with pagesz 0x40000000
mmap 0x200000@0x7f1cbfe00000
touch 1 pages with pagesz 0x200000

really setup hugepage with:
	level 0 - lowmem 0x0, biosmem 0x200000, highmem 0x0
	level 1 - lowmem 0x80000000, biosmem 0x0, highmem 0x80000000
vm_init_vdevs
No pm notify channel given
pci init hostbridge

pci init lpc

pci init passthru

polling 37...
Listening 37...
pci init virtio-blk

pci init virtio-net

pci init igd-lpc

tpm: init_vtpm2:Invalid socket path!
acrn_sw_load
SW_LOAD: partition blob /usr/share/acrn/bios/OVMF.fd size 0x200000 copied to addr 0x7f1cbfe00000
SW_LOAD: build e820 6 entries to addr: 0x7f1bc00ef008

SW_LOAD: entry[0]: addr 0x0000000000000000, size 0x00000000000a0000,  type 0x1

SW_LOAD: entry[1]: addr 0x0000000000100000, size 0x000000003b6fc000,  type 0x1

SW_LOAD: entry[2]: addr 0x000000003b7fc000, size 0x0000000004004000,  type 0x2

SW_LOAD: entry[3]: addr 0x000000003f800000, size 0x0000000040800000,  type 0x1

SW_LOAD: entry[4]: addr 0x00000000e0000000, size 0x0000000020000000,  type 0x2

SW_LOAD: entry[5]: addr 0x0000000100000000, size 0x0000000080000000,  type 0x1

SW_LOAD: ovmf_entry 0xfffffff0
add_cpu

2021-05-13 15:13 UTC, gvancuts requested changes
A general comment, I would like to see a bit more attention paid to the documentation for each function. I know some of the function names are kind of self-explanatory but if you land on a documentation page, read about the brief explanation of a function just to see that it's the name of the function itself, it does not add any value (and makes it look like the programmer did not care much). Let's try to do a better job there ;-)

2021-05-13 15:13 UTC, gvancuts commented on hypervisor/include/arch/x86/asm/tsc.h
> + * @brief read tsc.
Can you be a bit more verbose here, i.e.: 
```suggestion
 * @brief Read Time Stamp Counter (TSC)
```

2021-05-13 15:13 UTC, gvancuts commented on hypervisor/include/arch/x86/asm/tsc.h
> + * @return tsc value
Same comment here, could you be a bit more verbose, e.g.:
```suggestion
 * @return Returns the TSC value (in ticks)
```

2021-05-13 15:13 UTC, gvancuts commented on hypervisor/include/arch/x86/asm/tsc.h
> + * @brief  Get tsc.
Same comment, can you be more verbose. What is the difference between `read tsc` and `get tsc` for example? I kind of guess that it's mainly about the unit used for the return value, is that it? In any case, more verbose text for the `@brief` and `@return` strings should make it immediately clear what the difference is (and what the function is about).

2021-05-13 15:13 UTC, gvancuts commented on hypervisor/include/common/delay.h
> + * Copyright (C) 2021 Intel Corporation. All rights reserved.
```suggestion
 * Copyright (C) 2021 Intel Corporation.
```

2021-05-13 15:13 UTC, gvancuts commented on hypervisor/include/arch/x86/asm/tsc.h
> + * @brief Calibrate tsc.
Same comment. The explanation here is exactly the name of the function.

2021-05-13 15:13 UTC, gvancuts commented on hypervisor/include/common/ticks.h
> + * Copyright (C) 2021 Intel Corporation. All rights reserved.
```suggestion
 * Copyright (C) 2021 Intel Corporation.
```

2021-05-13 15:13 UTC, gvancuts commented on hypervisor/include/hw/hw_timer.h
> + * Copyright (C) 2018 Intel Corporation. All rights reserved.
If new file:
```suggestion
 * Copyright (C) 2021 Intel Corporation.
```

2021-05-14 00:58 UTC, wenlingz commented
@ylian16 usually code PR and doc PR are generated separately

2021-05-14 03:57 UTC, dongyaozu approved these changes

2021-05-17 07:21 UTC, dongyaozu approved these changes

2021-05-18 08:43 UTC, merged