doc: clean legacy software SRAM names
projectacrn/acrn-hypervisor pull request #6018
Opened 2021-05-14 06:47 UTC by yonghuah

psram is legacy name of SSRAM, rename it to ssam

Signed-off-by: Yonghua Huang <yonghua.huang@intel.com>

2021-05-14 15:19 UTC, fitchbe approved these changes

2021-05-16 17:57 UTC, gvancuts requested changes
Can you fix the typo in your commit message; `ssam` -> `ssram`

There is another instance of `pSRAM` in `devicemodel/core/sw_load_common.c`, line 227. Can you fix it too?

2021-05-16 17:57 UTC, gvancuts commented on doc/user-guides/acrn-dm-parameters.rst
>     This option enables Pseudo (Software) SRAM passthrough to the VM.
We could also update this free-text explanation to:
```suggestion
   This option enables Software SRAM passthrough to the VM.
```

2021-05-17 02:21 UTC, yonghuah commented
@gvancuts  thank you for this catch, have updated this PR, pls review.

-Yonghua

2021-05-17 02:22 UTC, ywan170 approved these changes

2021-05-17 07:31 UTC, gvancuts approved these changes
Thanks!

2021-05-17 07:34 UTC, merged