config_tools: add hybrid, hybrid_rt, logical partition scenario on ad…
projectacrn/acrn-hypervisor pull request #6164
Opened 2021-06-07 10:27 UTC by szhen11

…l board

add hybrid, hybrid_rt, logical_partition scenario and add launch
config xml on adl-s-crb board, add launch config xml on adl-rvp board.

Tracked-On: #5929
Signed-off-by: Shuang Zheng <shuang.zheng@intel.com>

2021-06-07 12:04 UTC, gvancuts requested changes
A couple of issues with this PR:
1. It adds a number of files for a new board (`adl-s-crb`) but no such `adl-s-crb.xml` that describes the board itself
2. We are adding yet another board to the list, we should revisit our strategy around these here (and involved the UX/DX in the conversation)

2021-06-07 12:04 UTC, gvancuts commented on misc/config_tools/data/adl-s-crb/logical_partition.xml
> +      <bootargs>        rw rootwait root=/dev/sda3 console=ttyS0 noxsave nohpet no_timer_check ignore_loglevel log_buf_len=16M consoleblank=0 tsc=reliable reboot=acpi
Same question about the leading spaces

2021-06-07 12:04 UTC, gvancuts commented on misc/config_tools/data/adl-s-crb/logical_partition.xml
> +      <bootargs>        rw rootwait root=/dev/sda3 console=ttyS0 noxsave nohpet no_timer_check ignore_loglevel log_buf_len=16M
Leading spaces?

2021-06-08 03:27 UTC, szhen11 commented on misc/config_tools/data/adl-rvp/industry_launch_2uos.xml
> +<acrn-config board="adl-s-crb" scenario="industry" uos_launcher="2">
sorry for this mistake, will update the board attribute value to adl-rvp.

2021-06-08 03:28 UTC, szhen11 commented on misc/config_tools/data/adl-s-crb/hybrid_rt.xml
> +      <bootargs>            rw rootwait console=tty0 consoleblank=0 no_timer_check quiet loglevel=3
will remove the leading space then.

2021-06-08 03:28 UTC, szhen11 commented on misc/config_tools/data/adl-s-crb/logical_partition.xml
> +      <bootargs>        rw rootwait root=/dev/sda3 console=ttyS0 noxsave nohpet no_timer_check ignore_loglevel log_buf_len=16M consoleblank=0 tsc=reliable reboot=acpi
will remove the leading space then.

2021-06-08 03:28 UTC, szhen11 commented on misc/config_tools/data/adl-s-crb/logical_partition.xml
> +      <bootargs>        rw rootwait root=/dev/sda3 console=ttyS0 noxsave nohpet no_timer_check ignore_loglevel log_buf_len=16M
will remove the leading space then.

2021-06-08 11:32 UTC, gvancuts commented on misc/config_tools/data/adl-rvp/industry_launch_2uos.xml
> +<acrn-config board="adl-s-crb" scenario="industry" uos_launcher="2">
> sorry for this mistake, will update the board attribute value to adl-rvp.

Thanks. How are we testing these files?

> and for adl-s-crb, it is another kind of board for alder lake-s platform, we put the board xml(adl-s-crb.xml) and scenario xmls into misc/config_tools/data/adl-s-crb/

I do not see this `adl-s-crb.xml` file in this PR, have I missed it?

2021-06-08 11:35 UTC, gvancuts commented
> 
> 
> …l board
> 
> add hybrid, hybrid_rt, logical_partition scenario and add launch
> config xml on adl-s-crb board, add launch config xml on adl-rvp board.

Can you polish up your commit message? E.g.:

```
config_tools: add 'adl-s-crb' board XMLs and launch script ('adl-rvp')

This commit adds the following data to the ACRN Configuration Tools:
* Board and scenario XMLs for a new board called 'adl-s-crb.xml'
* Add a new launch script for the 'adl-rvp' board
```

2021-06-08 11:37 UTC, gvancuts commented
I have lost track a bit of what gets generated by the tool and what we need to add manually as input for the tool... but aren't these XML files supposed to be generated by the ACRN Configuration Tool after one has fed it the `adl-s-crb.xml` board info and configured the scenarios? It does not seem like this was the process that was used here to create those. Can someone confirm this? @junjiemao1 @NanlinXie

2021-06-09 15:10 UTC, NanlinXie commented on misc/config_tools/data/adl-rvp/industry_launch_2uos.xml
> +<acrn-config board="adl-s-crb" scenario="industry" uos_launcher="2">
We have already launched the discussion for these board files location, let's keep this in v2.5 release.

2021-06-10 02:20 UTC, NanlinXie commented
> I have lost track a bit of what gets generated by the tool and what we need to add manually as input for the tool... but aren't these XML files supposed to be generated by the ACRN Configuration Tool after one has fed it the `adl-s-crb.xml` board info and configured the scenarios? It does not seem like this was the process that was used here to create those. Can someone confirm this? @junjiemao1 @NanlinXie

Usually we will upload the scenario files that our validation major use.

2021-06-10 02:20 UTC, NanlinXie approved these changes

2021-06-10 03:00 UTC, merged