doc: add missing parameters description of launch script xml
projectacrn/acrn-hypervisor pull request #6181
Opened 2021-06-08 22:46 UTC by yuchuyang

Add allow_trigger_s5, enable_ptm, console_vuart and communication_vuart
descriptions.

Tracked-On: #6138
Signed-off-by: Yang,Yu-chu <yu-chu.yang@intel.com>

2021-06-08 22:57 UTC, dbkinder requested changes

2021-06-08 22:57 UTC, dbkinder commented on doc/tutorials/acrn_configuration_tool.rst
> +  Allow vm to trigger s5 shutdown flow, this flag works with ``poweroff_channel``
```suggestion
  Allow VM to trigger s5 shutdown flow, this flag works with ``poweroff_channel``
```

2021-06-08 22:57 UTC, dbkinder commented on doc/tutorials/acrn_configuration_tool.rst
> +  'vuart1(pty)' and 'vuart1(tty)' only.
```suggestion
  ``vuart1(pty)`` and ``vuart1(tty)`` only.
```

2021-06-08 22:57 UTC, dbkinder commented on doc/tutorials/acrn_configuration_tool.rst
> +  Enable the Precision Timing Measurement(PTM) feature.
```suggestion
  Enable the Precision Timing Measurement (PTM) feature.
```

2021-06-08 22:57 UTC, dbkinder commented on doc/tutorials/acrn_configuration_tool.rst
> +  Enable a pci based console_vuart. Refer to :ref:`vuart_configuration` for details.
```suggestion
  Enable a PCI-based console vUART. Refer to :ref:`vuart_configuration` for details.
```

2021-06-08 22:57 UTC, dbkinder commented on doc/tutorials/acrn_configuration_tool.rst
> +  List of pci based communication vuart. Refer to :ref:`vuart_configuration` for details.
```suggestion
  List of PCI-based communication vUARTs. Refer to :ref:`vuart_configuration` for details.
```

2021-06-08 22:57 UTC, dbkinder commented on doc/tutorials/acrn_configuration_tool.rst
> +  Enable a pci based communication_vuart with its id. Refer to :ref:`vuart_configuration` for details.
```suggestion
  Enable a PCI-based communication vUART with its ID. Refer to :ref:`vuart_configuration` for details.
```

2021-06-09 00:21 UTC, wenlingz commented
@yuchuyang make doc fail

New errors/warnings found, please fix them:
==============================================

/home/acrn/workspace/make_doc/pme-yocto-build-make-doc-01/acrn-hypervisor/build/doc/rst/tutorials/acrn_configuration_tool.rst:345: WARNING: undefined label: vuart_configuration (if the link has no caption the label must precede a section header)
/home/acrn/workspace/make_doc/pme-yocto-build-make-doc-01/acrn-hypervisor/build/doc/rst/tutorials/acrn_configuration_tool.rst:348: WARNING: undefined label: vuart_configuration (if the link has no caption the label must precede a section header)
/home/acrn/workspace/make_doc/pme-yocto-build-make-doc-01/acrn-hypervisor/build/doc/rst/tutorials/acrn_configuration_tool.rst:351: WARNING: undefined label: vuart_configuration (if the link has no caption the label must precede a section header)

Makefile:65: recipe for target 'html' failed
make[1]: *** [html] Error 1
make[1]: Leaving directory '/home/acrn/workspace/make_doc/pme-yocto-build-make-doc-01/acrn-hypervisor/doc'
Makefile:129: recipe for target 'doc' failed
make: *** [doc] Error 2
+ error make doc
++ timestamp
++ date +%T
+ echo '07:08:45 ERROR: make doc'
07:08:45 ERROR: make doc

2021-06-09 20:58 UTC, yuchuyang commented
@wenlingz  updated the tag of reference.
Have verified locally, it works, thanks.

2021-06-09 21:28 UTC, dbkinder approved these changes
LGTM, thanks!

2021-06-09 21:28 UTC, merged