docE: Update address to report security vulnerability
projectacrn/acrn-hypervisor pull request #6267
Opened 2021-06-30 05:53 UTC by yonghuah

acrn-security@lists.projectacrn.org shall be used.

Signed-off-by: Yonghua Huang <yonghua.huang@intel.com>

2021-07-01 01:51 UTC, yonghuah commented
@NanlinXie please review

2021-07-02 02:35 UTC, NanlinXie commented
@yaomichael , please help to review.

2021-07-07 20:57 UTC, dbkinder commented on README.rst
> +  security vulnerability in ACRN, please send an e-mail to acrn-security@lists.projectacrn.org.
We can't merge this PR until the acrn-security mailing list is established.

2021-07-07 21:02 UTC, dbkinder requested changes
Don't merge until mailing list for acrn-security is established.

2021-07-12 18:46 UTC, dbkinder approved these changes
acrn-security@lists.projectacrn.org is established now.

2021-07-12 18:52 UTC, dbkinder commented
@hwang37 Are you OK with this change?

2021-07-13 02:06 UTC, hwang37 commented
Agree with David.

2021-07-13 23:24 UTC, merged