Makefile:add targz-pkg entry in Makefile
projectacrn/acrn-hypervisor pull request #6356
Opened 2021-08-05 06:41 UTC by liuhang-bit

User could use make targz-pkg command to generate tar package in
build directory,which could help user simplify the process
of installing acrn hypervisor in target board. user need to copy the
tarball package to target board,and extract it to "/" directory.

Tracked-On: #6355
Signed-off-by: liu hang1 <hang1.liu@intel.com>
Reviewed-by: VanCutsem, Geoffroy <geoffroy.vancutsem@intel.com>
Acked-by: Wang, Yu1 <yu1.wang@intel.com>

2021-08-05 06:58 UTC, gvancuts requested changes

2021-08-05 06:58 UTC, gvancuts commented on Makefile
> +FULL_VERSION=$(MAJOR_VERSION).$(MINOR_VERSION)$(EXTRA_VERSION)
This should be on the same line as `export`.

2021-08-05 07:56 UTC, wenlingz commented
OK to verify

2021-08-05 07:56 UTC, wenlingz commented
try verify EHL

2021-08-05 07:57 UTC, wenlingz commented
OK to verify doc

2021-08-05 07:57 UTC, wenlingz commented
try verify ldra

2021-08-05 10:41 UTC, gvancuts approved these changes

2021-08-05 11:39 UTC, gvancuts commented
One thing I've noticed that seems odd to me, is that `make install` seems to re-trigger a lot of build operations. Is this expected?

Take the following sequence:
```
make BOARD=nuc7i7dnb SCENARIO=industry
make targz-pkg
```
I would expect that running `make targz-pkg` would just create the tarball out of the build artefacts that were created in the previous step. But instead, it recompiles a bunch of stuff again, is it normal?

/cc @junjiemao1

2021-08-05 11:40 UTC, gvancuts requested changes

2021-08-05 11:40 UTC, gvancuts commented on Makefile
> +.PHONY: targz-pkg
```suggestion
.PHONY: targz-pkg
```

2021-08-05 11:40 UTC, gvancuts commented on Makefile
> +	tar -zcvf $(ROOT_OUT)/acrn-$(FULL_VERSION).tar.gz *
```suggestion
	tar -zcvf $(ROOT_OUT)/acrn-$(FULL_VERSION).tar.gz *
```

2021-08-08 06:08 UTC, NanlinXie approved these changes

2021-08-09 03:51 UTC, NanlinXie commented
> One thing I've noticed that seems odd to me, is that `make install` seems to re-trigger a lot of build operations. Is this expected?
> 
> Take the following sequence:
> 
> ```
> make BOARD=nuc7i7dnb SCENARIO=industry
> make targz-pkg
> ```
> 
> I would expect that running `make targz-pkg` would just create the tarball out of the build artefacts that were created in the previous step. But instead, it recompiles a bunch of stuff again, is it normal?
> 
> /cc @junjiemao1

We root caused, but we need do more validation to limit the impact. @liuhang-bit  will file PR later.
Created https://github.com/projectacrn/acrn-hypervisor/issues/6365 to tracked.
Let's merge this change firstly.

2021-08-09 03:52 UTC, merged