add acrn-dm -emul parameter list
projectacrn/acrn-hypervisor pull request #6440
Opened 2021-08-19 05:14 UTC by liuhang-bit

add acrn-dm -emul parameter list in the end of acrn-dm paramter charpter.

2021-08-19 11:02 UTC, gvancuts requested changes
Thanks for kicking this off @liuhang-bit 

I have not done a complete and thorough review yet, but there are a couple of high-level comments on this:
* Can you add all parameters that each of these can take?
* Can you be more verbose for some, e.g. `virtio-hdcp` meaning it's a `Virtio hdcp` device isn't bringing a lot of information to the user, how do they use it, etc.
* Capitalization is important in the documentation, so I expect to see `HDCP` instead of `hdcp` for example

2021-08-20 06:51 UTC, NanlinXie commented
Closed due to duplicated with #6445.

2021-08-20 06:51 UTC, closed without merging

2021-08-23 00:24 UTC, liuhang-bit commented on doc/user-guides/acrn-dm-parameters.rst
> +     - Usb controller used to support USB3.0 devices, provide downward compatibility
yes

2021-08-23 00:25 UTC, liuhang-bit commented on doc/user-guides/acrn-dm-parameters.rst
> +     - Advanced Host Controller Interface used to connect with AT Attachment Packet Interface device
CD-Rom is one of AT Attachment Packet Interface type device,i will add it as an example

2021-08-23 00:26 UTC, liuhang-bit commented on doc/user-guides/acrn-dm-parameters.rst
> +   * - "ahci-cd"
It seems like ahci-hd and ahci is the same in the code

2021-08-23 00:28 UTC, liuhang-bit commented on doc/user-guides/acrn-dm-parameters.rst
> +   * - "virtio-blk"
they are all the acrn-dm  -emul parameter ,the example of how to use -emul is in the doc of device model parameter

2021-08-23 11:37 UTC, gvancuts commented on doc/user-guides/acrn-dm-parameters.rst
> +     - Usb controller used to support USB3.0 devices, provide downward compatibility
Thanks, can you make this more explicit in the text.

2021-08-23 11:37 UTC, gvancuts commented on doc/user-guides/acrn-dm-parameters.rst
> +     - Advanced Host Controller Interface used to connect with AT Attachment Packet Interface device
Thanks

2021-08-23 11:38 UTC, gvancuts commented on doc/user-guides/acrn-dm-parameters.rst
> +   * - "ahci-cd"
I agree, can we add it to the list and indicate it's an alias?

2021-08-23 11:54 UTC, gvancuts commented on doc/user-guides/acrn-dm-parameters.rst
> +   * - "virtio-blk"
Not really, what I'm asking to have included here are all the options that `virtio-blk` can take. In the case of `virtio-blk` these are listed in the HLD (see [here](https://projectacrn.github.io/latest/developer-guides/hld/virtio-blk.html#usage)) but 1) I'm not sure these are still accurate and 2) we should make those explicitly part of this guide (or at a minimum reference some other place in our doc where to find them).

We should do this (i.e. detail all options) for **all** the `emul` types in this doc.

2021-09-03 03:22 UTC, liuhang-bit commented on doc/user-guides/acrn-dm-parameters.rst
> +     - Used for PAVP session management
protected audio and visual path used for user vm to protect their audio and visual content