doc: terminology cleanup in enable s5 guide
projectacrn/acrn-hypervisor pull request #6814
Opened 2021-11-10 22:55 UTC by amyreye

- Replace SOS or Service OS with Service VM
- Replace UOS or User OS with User VM
- Clean up some of the grammar

Signed-off-by: Amy Reyes <amy.reyes@intel.com>

2021-11-10 23:27 UTC, fitchbe approved these changes

2021-11-10 23:27 UTC, fitchbe commented on doc/tutorials/enable_s5.rst
> +      this command needs to be run before powering off the Service VM.
"this command needs to be run before powering off the Service VM" is one of those subject-object mix-ups due to the passive voice. You can either be explicit about who or what powers off the VM, or you can go with the _total-passivity_ option ("this commend needs to be run before the Service VM is powered off").

2021-11-11 00:19 UTC, dbkinder requested changes

2021-11-11 00:19 UTC, dbkinder commented on doc/tutorials/enable_s5.rst
> +   the launch script of that VM. And, only one VM in the system can be
```suggestion
   the launch script of that VM. Only one VM in the system can be
```

2021-11-11 00:19 UTC, dbkinder commented on doc/tutorials/enable_s5.rst
> +   .. code-block:: none
As @gvancuts would ask, let's get rid of these command prompts.  (Command lines with a ``#`` should use ``sudo``)

2021-11-11 00:19 UTC, dbkinder commented on doc/tutorials/enable_s5.rst
> +    Device Model. The channel from the Service VM to the User VM is as follows:
The text on lines 36-40 is indented too far (two spaces).  Same problem on lines 44-40.

2021-11-11 00:19 UTC, dbkinder commented on doc/tutorials/enable_s5.rst
> +   using this command:
Can you also fix the indenting here too.

2021-11-11 12:17 UTC, gvancuts approved these changes
LGTM. Beware that big changes are coming for the Lifecylce Manager (see #6789) and this document will have to be largely re-written.

2021-11-22 15:59 UTC, dbkinder commented
@amyreye PR has merge conflicts that need fixing :(

2021-11-22 19:55 UTC, amyreye commented
> @amyreye PR has merge conflicts that need fixing :(

Since the edits on master were substantial and addressed the SOS/UOS terminology issue, I will close this PR. I will then open a new one to address the grammatical and formatting issues that were brought up in the comments.

2021-11-22 19:55 UTC, closed without merging