doc: terminology cleanup in DM readme
projectacrn/acrn-hypervisor pull request #6828
Opened 2021-11-12 19:23 UTC by amyreye

- Replace SOS or Service OS with Service VM
- Clean up some of the grammar

Signed-off-by: Amy Reyes <amy.reyes@intel.com>

2021-11-12 23:15 UTC, dbkinder requested changes

2021-11-12 23:15 UTC, dbkinder commented on devicemodel/README.rst
> +VM. You can find out more about Project ACRN on the `Project ACRN
We can leave off the "You can find more about..." since we're actually  reading that documentation :)

2021-11-15 22:05 UTC, gvancuts approved these changes

2021-11-24 14:28 UTC, dbkinder approved these changes

2021-11-24 14:29 UTC, merged