doc: terminology cleanup in RTC virt
projectacrn/acrn-hypervisor pull request #6829
Opened 2021-11-12 19:29 UTC by amyreye

- Replace SOS or Service OS with Service VM
- Clean up some of the grammar

Signed-off-by: Amy Reyes <amy.reyes@intel.com>

2021-11-12 19:34 UTC, fitchbe approved these changes

2021-11-12 19:34 UTC, fitchbe commented on doc/developer-guides/hld/rtc-virt-hld.rst
> +port 0x71. Reads to the CMOS RAM offsets are fetched by reading the CMOS
"Reads…are fetched by reading…" (?): Recommend a slight rewrite.

2021-11-12 23:13 UTC, dbkinder requested changes

2021-11-12 23:13 UTC, dbkinder commented on doc/developer-guides/hld/rtc-virt-hld.rst
> +ACRN Device Model.
Seems like we should expand the RTC acronym on first use here (Real Time Clock)

2021-11-12 23:13 UTC, dbkinder commented on doc/developer-guides/hld/rtc-virt-hld.rst
> +RTVM. It supports RW for the CMOS address port 0x70 and RO for the CMOS data
Let' expand these too: RW -> Read/Write, RO -> Read only

2021-11-22 18:40 UTC, dbkinder approved these changes

2021-11-22 18:40 UTC, merged