dm: minor fix: add check for malloc result
projectacrn/acrn-hypervisor pull request #6860
Opened 2021-11-18 09:02 UTC by YuanyuanZhao609

Add check for malloc result to madt pointer.

Tracked-On: #6769
Signed-off-by: Yuanyuan Zhao <yuanyuan.zhao@linux.intel.com>

2021-11-19 07:56 UTC, gvancuts requested changes

2021-11-19 07:56 UTC, gvancuts commented on devicemodel/hw/platform/acpi/acpi_parser.c
> +		pr_err("Fail to malloc %d bytes for madt!\n", file_state.st_size);
```suggestion
		pr_err("Failed to malloc %d bytes for MADT!\n", file_state.st_size);
```

2021-11-22 06:04 UTC, YuanyuanZhao609 commented on devicemodel/hw/platform/acpi/acpi_parser.c
> +		pr_err("Fail to malloc %d bytes for madt!\n", file_state.st_size);
Will update in next version.

2021-11-22 07:51 UTC, gvancuts approved these changes

2021-11-24 11:13 UTC, wenlingz commented
@yakuizhao please help approve this PR,thanks

2021-11-24 12:46 UTC, wenlingz commented
@ywan170 please help approve this PR, thanks

2021-11-25 05:23 UTC, yakuizhao approved these changes
LGTM

2021-11-25 05:40 UTC, merged