doc: update two scheduling algorithm
projectacrn/acrn-hypervisor pull request #6900
Opened 2021-11-25 06:07 UTC by yfliuuu

Add description for the IORR (IO sensitive Round Robin) scheduler
and the priority based scheduler.

Signed-off-by: Jie Deng <jie.deng@intel.com>
Signed-off-by: Yifan Liu <yifan1.liu@intel.com>

2021-11-25 06:08 UTC, acrnsi commented
Can one of the admins verify this patch?

2021-11-25 06:09 UTC, yfliuuu commented
Continuation of PR #6615

2021-11-25 12:35 UTC, gvancuts approved these changes

2021-11-25 13:46 UTC, dbkinder requested changes
Looks good, with a few edits.

2021-11-25 13:46 UTC, dbkinder commented on doc/tutorials/cpu_sharing.rst
> +  we have two VM, one VM can be configured to use **PRIO_LOW** and the
```suggestion
  we have two VMs: one VM can be configured to use **PRIO_LOW** and the
```

2021-11-25 13:46 UTC, dbkinder commented on doc/tutorials/cpu_sharing.rst
> +  other one to use **PRIO_HIGH**, then the vCPU of the **PRIO_LOW** VM can
```suggestion
  other one to use **PRIO_HIGH**. The vCPU of the **PRIO_LOW** VM can
```

2021-11-25 13:46 UTC, dbkinder commented on doc/tutorials/cpu_sharing.rst
> +  only be running when the vCPU of the "PRIO_HIGH" VM voluntarily relinquish
```suggestion
  only be running when the vCPU of the **PRIO_HIGH** VM voluntarily relinquishes
```

2021-11-25 13:46 UTC, dbkinder commented on doc/tutorials/cpu_sharing.rst
> +  the usage of the pCPU.
```suggestion
  usage of the pCPU.
```

2021-11-26 00:49 UTC, yfliuuu commented
Re-pushed and comments fixed. @dbkinder

2021-11-26 01:19 UTC, dbkinder approved these changes
Thanks

2021-11-26 01:19 UTC, merged