doc: update GSG and partitioned documentation
projectacrn/acrn-hypervisor pull request #6970
Opened 2021-12-13 09:04 UTC by jackwhich

1. Update launch script and replace the "apt-get" command with "apt" in GSG documentation.
2. Update the tag to v2.7 in partitioned documentation.

Signed-off-by: zhongzhenx.liu <zhongzhenx.liu@intel.com>

2021-12-13 09:04 UTC, acrnsi commented
Can one of the admins verify this patch?

2021-12-13 14:46 UTC, gvancuts commented on doc/getting-started/getting-started.rst
> +
Looks like you have extra spaces here.
```suggestion

```

2021-12-13 14:46 UTC, gvancuts commented on doc/getting-started/getting-started.rst
> +      acrn-dm -A -m $mem_size -s 0:0,hostbridge \
Is this consistent with how the tool generates the launch script?

2021-12-13 16:57 UTC, dbkinder requested changes
Looks good, with a couple of edits

2021-12-13 16:57 UTC, dbkinder commented on doc/getting-started/getting-started.rst
> +         Please copy this file :file:`cp ~/acrn-work/acrn-hypervisor/build/hypervisor/serial.conf $disk/`
```suggestion
         Please copy the ``serial.conf`` file using::
         
            cp ~/acrn-work/acrn-hypervisor/build/hypervisor/serial.conf $disk/                 
```

2021-12-14 06:04 UTC, dbkinder approved these changes
other than @gvancuts question, LGTM.

2021-12-14 18:46 UTC, dbkinder commented
I found a bug in the GSG that requires quoting the uses of "$disk" (it might contain a space).  That PR was recently merged and introduced a merge conflict with your PR.   A rebase should make things better...

2021-12-15 10:24 UTC, gvancuts requested changes

2021-12-15 10:24 UTC, gvancuts commented on doc/getting-started/getting-started.rst
> +         -s 9,virtio-blk,./YaaG.img \
That's not consistent with the statement a few lines above, can you fix it?

2021-12-15 10:24 UTC, gvancuts commented on doc/getting-started/getting-started.rst
> +      acrn-dm -A -m $mem_size -s 0:0,hostbridge \
?

2021-12-15 20:28 UTC, dbkinder requested changes

2021-12-15 21:37 UTC, dbkinder approved these changes
I made my recommended changes directly to your branch.  LGTM now, thanks!

2021-12-15 21:37 UTC, merged