doc: editorial cleanup in enable s5 guide
projectacrn/acrn-hypervisor pull request #7012
Opened 2022-01-07 19:35 UTC by amyreye

- Address grammar and formatting comments from PR #6814
- General grammar cleanup

Signed-off-by: Reyes, Amy <amy.reyes@intel.com>

2022-01-07 19:36 UTC, acrnsi commented
Can one of the admins verify this patch?

2022-01-07 20:18 UTC, dbkinder commented
@wenlingz @NanlinXie BUILD DOC failed shows no reason for failure

2022-01-07 20:36 UTC, dbkinder requested changes

2022-01-07 20:36 UTC, dbkinder commented on doc/tutorials/enable_s5.rst
> +    ``/dev/ttySn``. For the User VM with the minimal VM ID, the communication
I suspect ``lowest`` is the right term to use here, instead of ``minimal``.

2022-01-07 20:36 UTC, dbkinder commented on doc/tutorials/enable_s5.rst
> +   a. Copy ``life_mngr.conf``, ``s5_trigger_linux.py``, ``life_mngr``,
These command examples assumes there's a network connection between the development and target.  We might mention that and say you can also use a USB stick to transfer files.

2022-01-12 18:02 UTC, dbkinder requested changes
LGTM after a couple tweaks...

2022-01-12 18:02 UTC, dbkinder commented on doc/tutorials/enable_s5.rst
> +  .. note:: These vUARTs are emulated in the hypervisor; expose the node as
The indenting on this note isn't quite right.

2022-01-12 18:02 UTC, dbkinder commented on doc/tutorials/enable_s5.rst
> +    configured as invalid; the communication vUART id should be 2 or others.
```suggestion
    configured as invalid; the communication vUART id should be 2 or higher.
```

2022-01-12 18:36 UTC, dbkinder approved these changes
LTGM, thanks!

2022-01-13 01:19 UTC, merged