config_tools: Update Configurator UI XSD
projectacrn/acrn-hypervisor pull request #7213
Opened 2022-03-23 20:31 UTC by amyreye

- Update XSD files to match field names and tooltips in parameter spreadsheet

Tracked-On: #5692
Signed-off-by: Reyes, Amy <amy.reyes@intel.com>

2022-03-23 20:31 UTC, acrnsi commented
Can one of the admins verify this patch?

2022-03-23 22:17 UTC, dbkinder requested changes
Good start on these...

2022-03-23 22:17 UTC, dbkinder commented on misc/config_tools/schema/config.xsd
> +        <xs:documentation>Enable the software workaround for Machine Check Error on Page Size Change (hardware bug in some processor families).</xs:documentation>
Is that the correct wording (hardware bug)?

2022-03-23 22:17 UTC, dbkinder commented on misc/config_tools/schema/config.xsd
> +        <xs:documentation>Specify the maximum number of PCI devices. The default value is calculated from the board configuration file. If you have PCI devices that were not detected by the Board Ins
We should mention this impacts the amount of memory used to maintain information about these PCI devices.

2022-03-23 22:17 UTC, dbkinder commented on misc/config_tools/schema/config.xsd
> +          <xs:documentation>Specify the maximum number of MSI-X tables per device. The default value is calculated from the board configuration file.</xs:documentation>
```suggestion
          <xs:documentation>Specify the maximum number of Message Signaled Interrupt  MSI-X tables per device. The default value is calculated from the board configuration file.</xs:documentation>
```

2022-03-23 22:17 UTC, dbkinder commented on misc/config_tools/schema/config.xsd
> +	<xs:documentation>Select the OS type for this VM. This is required to run Windows in a User VM. See documentation for how to include this in the Device Model arguments.</xs:documentation>
Need a link to the documentation.

2022-03-23 22:17 UTC, dbkinder commented on misc/config_tools/schema/config.xsd
> +        <xs:documentation>Select the VM type. A standard VM is for general-purpose applications, such as human-machine interface (HMI). A real-time VM offers special features for time-sensitive appli
We should use the actual VM Type values in this explanation:
```suggestion
        <xs:documentation>Select the VM type. A standard VM (``STANDARD_VM``) is for general-purpose applications, such as human-machine interface (HMI). A real-time VM (``RTVM``) offers special features for time-sensitive applications.</xs:documentation>
```

2022-03-24 00:50 UTC, amyreye commented on misc/config_tools/schema/config.xsd
> +        <xs:documentation>Enable the software workaround for Machine Check Error on Page Size Change (hardware bug in some processor families).</xs:documentation>
In my previous project, "silicon" was considered slang.

2022-03-24 03:29 UTC, NanlinXie approved these changes

2022-03-25 07:06 UTC, merged

2022-03-25 18:08 UTC, dbkinder commented
@NanlinXie Why was this PR merged with unresolved change requests :(