Refine for HPAn setting
projectacrn/acrn-hypervisor pull request #7304
Opened 2022-04-18 11:21 UTC by weichenli-intel

The current code only supports 2 HPA regions per VM.

So we redesign and extended ACRN to support 2+ HPA regions per VM,
to use host memory better if it is scatted among multiple regions.

This series of patches also change the offline tool to adapter the HPAn
setting, include the schema and xsl change to generate .c and .h.

This patch depend on the config allocate HPA patch.

2022-04-18 11:22 UTC, acrnsi commented
Can one of the admins verify this patch?

2022-04-18 16:42 UTC, amyreye commented on misc/config_tools/schema/VMtypes.xsd
> +        <xs:documentation>Physical memory segmentation</xs:documentation>
```suggestion
        <xs:documentation>Specify the starting address for non-contiguous allocation.</xs:documentation>
```

2022-04-18 16:42 UTC, amyreye commented on misc/config_tools/schema/VMtypes.xsd
> +        <xs:documentation>Size (MB)</xs:documentation>
```suggestion
        <xs:documentation>Specify the physical memory size for non-contiguous allocation in megabytes. The size is a subset of the VM's total memory size specified on the Basic tab.</xs:documentation>
```

2022-04-18 16:42 UTC, amyreye commented on misc/config_tools/schema/VMtypes.xsd
> +    <xs:element name="whole" type="xs:integer" default="256">
Change `name="whole"` to `name="size"` as specified in the parameter spreadsheet Column C "Proposed parameter"?

2022-04-18 16:42 UTC, amyreye commented on misc/config_tools/schema/VMtypes.xsd
> +      <xs:annotation acrn:title="physical memory region" acrn:views="advanced" acrn:applicable-vms="pre-launched" >
Please check the PPT and confirm whether this element is "region" or "segmentation".

```suggestion
      <xs:annotation acrn:title="Physical memory segmentation" acrn:views="advanced" acrn:applicable-vms="pre-launched" >
```

2022-04-18 16:42 UTC, amyreye commented on misc/config_tools/schema/config.xsd
>          <xs:documentation>Specify memory information for Service and User VMs.</xs:documentation>
Change the documentation at line 363 to `<xs:documentation>Specify memory information for User VMs.</xs:documentation>`.  This element doesn't define memory for Service VM.

2022-04-18 16:45 UTC, dbkinder requested changes

2022-04-18 16:45 UTC, dbkinder commented on misc/config_tools/schema/VMtypes.xsd
> +        <xs:documentation>Physical memory region</xs:documentation>
The documentation needs to be more than a repeat of the field title.  Add an explanation that includes this is for pre-launched VMs only.  What are the value restrictions?

2022-04-18 16:49 UTC, dongyaozu approved these changes

2022-04-19 02:00 UTC, GGGZZZRRR commented
@weichenli-intel please add "Tracked on"

2022-04-19 05:31 UTC, dongyaozu approved these changes

2022-04-20 00:03 UTC, dongyaozu approved these changes

2022-04-20 04:21 UTC, dongyaozu approved these changes

2022-04-21 05:28 UTC, NanlinXie approved these changes

2022-04-21 05:53 UTC, GGGZZZRRR commented
@weichenli-intel please check this error 

+ git apply offline.patch
offline.patch:1454: trailing whitespace.
 
offline.patch:1529: trailing whitespace.
    
warning: 2 lines add whitespace errors.
+ rm offline.patch
+ '[' 0 -eq 0 ']'
+ cp -r ../virtualization.hypervisors.acrn.acrn-dev.acrn-offline-patch/boards/adl-p-lp5-rvp ../virtualization.hypervisors.acrn.acrn-dev.acrn-offline-patch/boards/adl-rvp ../virtualization.hypervisors.acrn.acrn-dev.acrn-offline-patch/boards/adl-s-crb ../virtualization.hypervisors.acrn.acrn-dev.acrn-offline-patch/boards/ehl-crb-b ../virtualization.hypervisors.acrn.acrn-dev.acrn-offline-patch/boards/icx-d-hcc ../virtualization.hypervisors.acrn.acrn-dev.acrn-offline-patch/boards/icx-rvp ../virtualization.hypervisors.acrn.acrn-dev.acrn-offline-patch/boards/tgl-rvp misc/config_tools/data/
+ cd misc/config_tools/
+ python3 scenario_config/validator.py --loglevel info
CRITICAL:root:/acrn-config/vm[1]: Unexpected child with tag 'memory' at position 5. Tag (priority | companion_vmid | console_vuart) expected.
CRITICAL:root:/acrn-config/vm[2]/memory: Unexpected child with tag 'whole' at position 1. Tag size expected.
CRITICAL:root:/acrn-config/vm[3]/memory: Unexpected child with tag 'whole' at position 1. Tag size expected.
CRITICAL:root:/acrn-config/vm[4]/memory: Unexpected child with tag 'whole' at position 1. Tag size expected.
CRITICAL:root:/acrn-config/vm[5]/memory: Unexpected child with tag 'whole' at position 1. Tag size expected.
CRITICAL:root:/acrn-config/vm[6]/memory: Unexpected child with tag 'whole' at position 1. Tag size expected.
CRITICAL:root:/acrn-config/vm[7]/memory: Unexpected child with tag 'whole' at position 1. Tag size expected.
ERROR:root:Board icx-d-hcc and scenario shared are inconsistent: 7 syntax errors, 0 data errors, 0 warnings.

2022-04-21 16:18 UTC, dongyaozu approved these changes

2022-04-22 01:15 UTC, szhen11 commented
@weichenli-intel CI failed by

Rule view:
   ----------------------------------------------
   Rule                                    Count
   ----------------------------------------------
   clang-analyzer-deadcode.DeadStores      1

File view:
   ---------------------------------------------
   File                                   Count
   ---------------------------------------------
   hypervisor/arch/x86/guest/ve820.c      1
   ---------------------------------------------
   Total                                  1
   ---------------------------------------------

All warnings:
/home/acrn/workspace/acrn-hypervisor-codescan-native_961/acrn-hypervisor/hypervisor/arch/x86/guest/ve820.c:296:3: warning: Value stored to 'gpa_start' is never read [clang-analyzer-deadcode.DeadStores]
                gpa_start = add_ram_entry((vm->e820_entries + entry_idx), gpa_start, gpa_hi_size);
                ^           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/acrn/workspace/acrn-hypervisor-codescan-native_961/acrn-hypervisor/hypervisor/arch/x86/guest/ve820.c:296:3: note: Value stored to 'gpa_start' is never read
                gpa_start = add_ram_entry((vm->e820_entries + entry_idx), gpa_start, gpa_hi_size);
                ^           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

2022-04-22 03:37 UTC, szhen11 commented
@weichenli-intel launch rtvm failed:
bash /home/auto_script/launch_user_vm_id2.sh
cpu8 online=1
cpu9 online=1
acrn-br0 bridge already exists, adding new RT TAP device to it...
Launch device model with parameters: --cpu_affinity 64,66 -m NoneM --ovmf /usr/share/acrn/bios/OVMF.fd -s 0:0,hostbridge --virtio_poll 1000000 -s 3,virtio-console,@stdio:stdio_port -s 4,virtio-net,tap=RT,mac_seed=88:88:88:88:87:88-POST_RT_VM1 -s 5,virtio-blk,/root/rt/core-image-weston-intel-corei7-64.wic --rtvm --lapic_pt --logger_setting console,level=4;kmsg,level=3;disk,level=5 POST_RT_VM1
acrn-dm: invalid memsize 'NoneM'
root@192168132sos-dom0:~#

2022-04-22 05:30 UTC, weichenli-intel commented
> @weichenli-intel CI failed by
> 
> ## Rule view:
> ## Rule Count
> clang-analyzer-deadcode.DeadStores 1
> 
> ## File view:
> ## File Count
> ## hypervisor/arch/x86/guest/ve820.c 1
> ## Total 1
> All warnings: /home/acrn/workspace/acrn-hypervisor-codescan-native_961/acrn-hypervisor/hypervisor/arch/x86/guest/ve820.c:296:3: warning: Value stored to 'gpa_start' is never read [clang-analyzer-deadcode.DeadStores] gpa_start = add_ram_entry((vm->e820_entries + entry_idx), gpa_start, gpa_hi_size); ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ /home/acrn/workspace/acrn-hypervisor-codescan-native_961/acrn-hypervisor/hypervisor/arch/x86/guest/ve820.c:296:3: note: Value stored to 'gpa_start' is never read gpa_start = add_ram_entry((vm->e820_entries + entry_idx), gpa_start, gpa_hi_size); ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Fixed.

2022-04-22 06:46 UTC, merged