config_tools: update configurator document and build script
projectacrn/acrn-hypervisor pull request #7374
Opened 2022-04-26 16:05 UTC by Weiyi-Feng

1. update configurator document.
2. fix build script doesn't generate allchecks.xsd issue.
3. add open_devtools command, now we can get detail debug info in prod.
4. remove vconsole component, which will cause some strange js runtime issue in Linux.

Tracked-On: #6691
Signed-off-by: Weiyi Feng <weiyix.feng@intel.com>

2022-04-26 16:06 UTC, acrnsi commented
Can one of the admins verify this patch?

2022-04-26 17:28 UTC, dbkinder requested changes
There's a typo in a pathname.
Also, the description should provide more information about what changes are being made.

2022-04-26 17:28 UTC, dbkinder commented on misc/config_tools/configurator/README.md
> +python scenario_config/jsnonschema/convert.py
```suggestion
python scenario_config/jsonschema/convert.py
```

2022-04-26 21:30 UTC, dbkinder requested changes
Thanks for adding better description.  There's still a typo in the path

2022-04-26 21:30 UTC, dbkinder commented on misc/config_tools/configurator/README.md
> +python scenario_config/jsnoschema/convert.py
```suggestion
python scenario_config/jsonschema/convert.py
```

2022-04-27 01:08 UTC, Weiyi-Feng commented on misc/config_tools/configurator/README.md
> +python scenario_config/jsnoschema/convert.py
Sorry for that...add it

2022-04-27 01:44 UTC, NanlinXie approved these changes

2022-04-27 02:27 UTC, dbkinder approved these changes
LGTM thanks

2022-04-27 04:54 UTC, merged