doc: Copyedit upgrading_configuration.rst
projectacrn/acrn-hypervisor pull request #7412
Opened 2022-05-05 22:02 UTC by amyreye

- Grammatical and formatting cleanup

Signed-off-by: Reyes, Amy <amy.reyes@intel.com>

2022-05-05 22:03 UTC, acrnsi commented
Can one of the admins verify this patch?

2022-05-06 18:51 UTC, dbkinder requested changes
A few additional tweaks...

2022-05-06 18:51 UTC, dbkinder commented on doc/tutorials/upgrading_configuration.rst
> +``<your scenario XML>`` as possible, based on the latest schema. If there is any
You've been using ``data`` as plural previously and in the next sentence, so for consistency:
```suggestion
``<your scenario XML>`` as possible, based on the latest schema. If there are any
```

2022-05-06 18:51 UTC, dbkinder commented on doc/tutorials/upgrading_configuration.rst
> +XML:
```suggestion
XML files into the merged format:
```

2022-05-06 18:51 UTC, dbkinder commented on doc/tutorials/upgrading_configuration.rst
> +The upgrader migrates all data in both XMLs and shows messages about
```suggestion
The upgrader migrates all data in both XMLs into the ``<out file>`` and shows messages about
```

2022-05-06 22:24 UTC, dbkinder approved these changes
LGTM, thanks!

2022-05-06 22:24 UTC, merged