config_tools: clean up configurator
projectacrn/acrn-hypervisor pull request #7509
Opened 2022-05-18 10:26 UTC by YuanyuanZhao609

This patch use 'make clean' to clean up the files left after
a 'make configurator'.

Tracked-On: #7508
Signed-off-by: Yuanyuan Zhao <yuanyuan.zhao@linux.intel.com>

2022-05-18 10:27 UTC, acrnsi commented
Can one of the admins verify this patch?

2022-05-19 03:54 UTC, NanlinXie approved these changes

2022-05-19 16:33 UTC, dbkinder requested changes

2022-05-19 16:33 UTC, dbkinder commented on misc/packaging/gen_acrn_deb.py
> +    add_cmd_list(cmd_list, 'bash -c "python ./configurator/packages/configurator/thirdLib/manager.py clean"', config_tools_path)
Looks like thirdLib/manager.py has a dependency that's not installed in the CI system:
```
Traceback (most recent call last):
  File "./configurator/packages/configurator/thirdLib/manager.py", line 14, in <module>
    from tqdm.auto import tqdm
ModuleNotFoundError: No module named 'tqdm'
cmd(bash -c "python ./configurator/packages/configurator/thirdLib/manager.py clean") run in dir(misc/config_tools) failed and exit
make: *** [Makefile:167: clean] Error 255
```

2022-05-20 03:00 UTC, szhen11 commented
start to run premerge test

2022-05-20 06:25 UTC, merged