config-tools: show enumNames in vuart select-form
projectacrn/acrn-hypervisor pull request #7565
Opened 2022-05-24 09:41 UTC by izhouwu

The vuart widget was showing enum values in select-form as options.
The correct way is to show enumNames instead of values.
The widget uses b-form which need different data structure for
select-form. So this patch added a transformation.

Also changed the label 'VBDF' to 'Virtual BDF' as an UX improvement.

Tracked-On: #7562
Signed-off-by: Wu Zhou <wu.zhou@intel.com>

2022-05-24 09:42 UTC, acrnsi commented
Can one of the admins verify this patch?

2022-05-24 18:14 UTC, amyreye commented
Please help me to understand: It looks like the above PR adds labels to the .vue file rather than exposing the labels from the acrn:title attribute in the XSD files. There are already good labels in the XSD files. Can the Configurator UI show the existing labels in the XSD files? We don't want to create different labels in the .vue files, because we also use the XSD files to generate documentation and we don't want a mismatch between the UI and documentation. Example of labels from VMtypes.xsd: 

<xs:complexType name="VuartEndpointType">
  <xs:sequence>
    <xs:element name="vm_name" type="xs:string">
      <xs:annotation **acrn:title="Virtual UART port"**>
        <xs:documentation>Virtual UART port</xs:documentation>
      </xs:annotation>
    </xs:element>
    <xs:element name="io_port" type="HexFormat" default="0x3F">
      <xs:annotation **acrn:title="Virtual I/O address"**>
        <xs:documentation>Specify the COM base for each legacy virtual UART.</xs:documentation>
      </xs:annotation>
    </xs:element>
    <xs:element name="vbdf" type="VBDFType">
      <xs:annotation **acrn:title="Virtual UART BDF"** acrn:defaults="[f'00:{i:02x}.0' for i in range(16, 24)]" acrn:unique-among="//vuart_connection/endpoint[vm_name=$parent/vm_name]/vbdf/text()">
        <xs:documentation>Specify the virtual Bus:Device.Function (BDF) for each PCI virtual UART. Virtual BDF is automatically assigned when the configuration is saved and can be changed if needed.</xs:documentation>
      </xs:annotation>
    </xs:element>
  </xs:sequence>
</xs:complexType>


<xs:simpleType name="VuartType">

  <xs:annotation>
    <xs:documentation>A string with value: ``legacy`` or ``pci``.</xs:documentation>
  </xs:annotation>
  <xs:restriction base="xs:string">
    <xs:enumeration value="legacy">
      <xs:annotation **acrn:title="Legacy"** />
    </xs:enumeration>
    <xs:enumeration value="pci">
      <xs:annotation **acrn:title="PCI"** />
    </xs:enumeration>
  </xs:restriction>
</xs:simpleType>


[Xie, Nanlin](https://github.com/secure/ViewProfile.jspa?name=xienanli) [Mao, Junjie](https://github.com/secure/ViewProfile.jspa?name=junjiema) Can we make it a common practice to always pull labels from the XSD files? cc: [Booth, Cory J](https://github.com/secure/ViewProfile.jspa?name=cjbooth) [Kinder, David B](https://github.com/secure/ViewProfile.jspa?name=dbkinder)

2022-05-24 18:18 UTC, amyreye requested changes

2022-05-24 18:38 UTC, dbkinder commented on misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/VUART.vue
> +            <b-col sm="4" v-else-if="VUARTConn.type === 'pci'"> Virtual BDF: </b-col>
Oh my, yes.  We must pull those names from the .xsd files as the master location for defining the labels and tooltips and option visibility and order. @junjiemao1 @NanlinXie

2022-05-25 11:41 UTC, izhouwu commented on misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/VUART.vue
> +            <b-col sm="4" v-else-if="VUARTConn.type === 'pci'"> Virtual BDF: </b-col>
This sounds right. I have rebased this PR. Now all the labels we used in the vUART widget comes from the XSD file.

2022-05-25 18:45 UTC, amyreye approved these changes

2022-05-26 01:33 UTC, GGGZZZRRR commented
start to run premerge test

2022-05-26 02:12 UTC, merged