ACRN: DM: Fix the vsock error info.
projectacrn/acrn-hypervisor pull request #7579
Opened 2022-05-25 07:10 UTC by liudlong

Replace the exclamation mark with period mark in debug info and fix
the Guest CID max value macro.

Tracked-On: #7456
Signed-off-by: Liu Long <long.liu@linux.intel.com>

2022-05-25 07:29 UTC, GGGZZZRRR commented
start to build

2022-05-25 12:38 UTC, gvancuts requested changes
@dbkinder , can you please review ?

2022-05-25 12:38 UTC, gvancuts commented on devicemodel/hw/pci/virtio/vhost_vsock.c
> +		pr_err(("Open vhost-vsock fail, pls open vsock kernel config.\n"));
We should rather ask the user to check his kernel config and point at the configuration variable to check on.

2022-06-08 05:55 UTC, szhen11 commented
@dbkinder Could you please review this PR？

2022-06-14 07:51 UTC, liudlong commented
Close the PR, because commit the "error info" in other PR and fix the comments

2022-06-14 07:51 UTC, closed without merging