config tool:add schema check for UI name validation
projectacrn/acrn-hypervisor pull request #7701
Opened 2022-06-06 15:07 UTC by liuhang-bit

ivshmem name and vuart connection vm name are required in UI, so
add the check in case user miss setting them.

Tracked-On: #7700
Signed-off-by: hangliu1 <hang1.liu@linux.intel.com>

2022-06-06 15:07 UTC, NanlinXie approved these changes

2022-06-06 15:08 UTC, acrnsi commented
Can one of the admins verify this patch?

2022-06-06 16:06 UTC, dbkinder requested changes

2022-06-07 00:11 UTC, liuhang-bit commented on misc/config_tools/schema/VMtypes.xsd
> +      <xs:annotation acrn:title="VM name">
OK I will change it to "vUART connection VM name"

2022-06-07 00:19 UTC, dbkinder approved these changes
LGTM, thanks.

2022-06-07 02:01 UTC, merged