misc: fix the schema check error
projectacrn/acrn-hypervisor pull request #7703
Opened 2022-06-06 16:00 UTC by weichenli-intel

The current code have not add annotation for RDT_ENABLED and
SSRAM_ENABLED check which cause a schema check error.

This patch add annotation and documentation to remind users.

Tracked-On: #6690
Signed-off-by: Chenli Wei <chenli.wei@intel.com>

2022-06-06 16:01 UTC, acrnsi commented
Can one of the admins verify this patch?

2022-06-06 16:10 UTC, dbkinder requested changes

2022-06-06 16:10 UTC, dbkinder commented on misc/config_tools/schema/checks/rdt_support.xsd
> +  <xs:assert test="not (//hv//RDT/RDT_ENABLED = 'y' and //hv//SSRAM/SSRAM_ENABLED = 'y')">
PR #7686 added this annotation.  We also need error messages to use the UI names for options not the XML element names.  (Also, there's no way for a developer to edit the RDT_ENABLED element using the configurator.)

I recommend this PR be closed without merging.

2022-06-07 02:09 UTC, dbkinder commented
This fix was made in PR #7686

2022-06-07 02:09 UTC, closed without merging