doc: add doc for required systemd services
projectacrn/acrn-hypervisor pull request #7739
Opened 2022-06-10 02:19 UTC by zhangqiang4

"systemd-networkd" is required for acrn-dm to create bridge device.
Document it in GSG before acrn network deb package is ready.

Tracked-On: #7738
Signed-off-by: Qiang Zhang <qiang4.zhang@intel.com>

2022-06-10 02:19 UTC, acrnsi commented
Can one of the admins verify this patch?

2022-06-10 20:49 UTC, amyreye approved these changes

2022-06-11 17:46 UTC, dbkinder requested changes
clarify what this command is used for

2022-06-11 17:46 UTC, dbkinder commented on doc/getting-started/getting-started.rst
> +#. Start systemd service required by device model:
```suggestion
#. Start the Service VM's system daemon for managing network configurations,
   allowing the Device Model to provide network access to User VMs:
```

2022-06-14 01:23 UTC, zhangqiang4 commented on doc/getting-started/getting-started.rst
> +#. Start systemd service required by device model:
ok

2022-06-14 04:40 UTC, dbkinder approved these changes

2022-06-14 04:41 UTC, merged