doc: Update vUART tutorial
projectacrn/acrn-hypervisor pull request #7809
Opened 2022-06-22 21:29 UTC by amyreye

- Update overview, dependencies and constraints
- Update to match Configurator UI instead of manually editing XML files
- Remove architectural details and instead point to high-level design documentation

Signed-off-by: Reyes, Amy <amy.reyes@intel.com>

2022-06-23 06:36 UTC, NanlinXie approved these changes

2022-06-23 22:58 UTC, dbkinder requested changes

2022-06-23 22:58 UTC, dbkinder commented on doc/tutorials/vuart_configuration.rst
> +vUART enables you to exchange data between the hypervisor and a VM
```suggestion
A vUART can exchange data between the hypervisor and a VM
```

2022-06-23 22:58 UTC, dbkinder commented on doc/tutorials/vuart_configuration.rst
> +or between two VMs. Typical use cases of vUART include:
```suggestion
or between two VMs. Typical use cases of a vUART include:
```

2022-06-23 22:58 UTC, dbkinder commented on doc/tutorials/vuart_configuration.rst
> +between two VMs, you can use the shared memory feature (by means of QEMU's
```suggestion
between two VMs, you can use the inter-VM shared memory feature
```

2022-06-23 22:58 UTC, dbkinder commented on doc/tutorials/vuart_configuration.rst
> +IVSHMEM) instead.
```suggestion
(IVSHMEM) instead.
```

2022-06-23 22:58 UTC, dbkinder commented on doc/tutorials/vuart_configuration.rst
> +* Although vUART is available to all kinds of VMs, it is not recommended to
```suggestion
* Although a vUART is available to all kinds of VMs, you should not
```

2022-06-23 22:58 UTC, dbkinder commented on doc/tutorials/vuart_configuration.rst
> +  enable vUART to access the console of or exchange data with a VM that needs to
```suggestion
  enable a vUART to access the console of or exchange data with a real-time VM.
```

2022-06-23 22:58 UTC, dbkinder commented on doc/tutorials/vuart_configuration.rst
> +  penalty that could delay the response of asynchronous events in those VMs.
```suggestion
  penalty that could delay the response of asynchronous events in real-time VMs.
```

2022-06-23 22:58 UTC, dbkinder commented on doc/tutorials/vuart_configuration.rst
> +The following steps show an example of how to configure and verify a vUART
```suggestion
The following steps show how to configure and verify a vUART
```

2022-06-24 18:22 UTC, dbkinder approved these changes
LGTM, thanks

2022-06-24 18:22 UTC, merged