doc: Update IVSHMEM tutorial
projectacrn/acrn-hypervisor pull request #7822
Opened 2022-06-24 22:28 UTC by amyreye

- Update overview, dependencies and constraints
- Update to match Configurator UI instead of manually editing XML files
- Remove architectural details and instead point to high-level design documentation

Signed-off-by: Reyes, Amy <amy.reyes@intel.com>

2022-06-24 22:29 UTC, acrnsi commented
Can one of the admins verify this patch?

2022-06-25 00:43 UTC, dbkinder requested changes

2022-06-25 00:43 UTC, dbkinder commented on doc/tutorials/enable_ivshmem.rst
> +   #. Check the inter-VM shared memory vail. Run the following commands in
vail?

2022-06-25 00:43 UTC, dbkinder commented on doc/tutorials/enable_ivshmem.rst
> +         root@acrn-Standard-PC-i440FX-PIIX-1996:~# ./ivshmem_test.bin uio0 tx test.file
this "ivhsmem_test.bin" executable doesn't exist and there are no instructions how to create it.

2022-06-25 00:43 UTC, dbkinder commented on doc/tutorials/enable_ivshmem.rst
> +      between the VMs. See :ref:`inter-vm_communication_ivshmem_app`. In this example, the application is ``ivshmem_test.bin``.
There are no instructions in that doc for how to create this app

2022-06-28 03:43 UTC, dbkinder approved these changes
OK, thanks.

2022-06-28 03:45 UTC, merged