[Release_3.0]modify elementpath version ==2.5.0
projectacrn/acrn-hypervisor pull request #7878
Opened 2022-07-07 07:36 UTC by wenlingz

modify elementpath version ==2.5.0

Tracked-On:projectacrn#6688
Signed-off-by: wenlingz <wenling.zhang@intel.com>

2022-07-07 07:36 UTC, acrnsi commented
Can one of the admins verify this patch?

2022-07-07 08:23 UTC, gvancuts commented
Can you fix your commit message to have a subject line and a message body?

2022-07-07 20:11 UTC, dbkinder requested changes

2022-07-11 01:52 UTC, wenlingz commented on debian/control
> +   python3-elementpath (== 2.5.0),
Modified, please check, thanks

2022-07-16 14:47 UTC, dbkinder approved these changes
LTGM, thanks.

2022-07-18 08:49 UTC, szhen11 commented
@yakuizhao Please help to approve this PR.

2022-07-19 00:17 UTC, yakuizhao approved these changes
LGTM

2022-07-19 02:21 UTC, merged