doc: update vUART tutorials
projectacrn/acrn-hypervisor pull request #7896
Opened 2022-07-18 06:58 UTC by weichenli-intel

The current code assign COM2 to S5 feature as a commutation vUART, so
the COM2's IO port which value is 0x2F8 could not assign to another
vUART connection.

This patch add a node and modify the legacy vUART sample, change the
default IO port to 0x3E8 which was known as COM3.

Tracked-On: #6690
Signed-off-by: Chenli Wei <chenli.wei@linux.intel.com>

2022-07-18 06:59 UTC, acrnsi commented
Can one of the admins verify this patch?

2022-07-18 18:10 UTC, dbkinder requested changes
I/O address changes to ``0x3F8`` for the example are not done everywhere in this doc.

2022-07-18 18:10 UTC, dbkinder commented on doc/tutorials/vuart_configuration.rst
> +   #. For the virtual I/O address, this example uses ``0x3E8``.
This text change says to use  ``0x3E8`` but the picture is using ``0x2E8`` and Line 143 below showing output from dmesg also is using ``0x2E8`` and talks about using ``/dev/ttyS1`` for testing the vUART communication.  These I/O addresses all need updating.

2022-07-18 18:10 UTC, dbkinder commented on doc/tutorials/vuart_configuration.rst
> +   .. note::
This note needs to be outdented to the left margin (that will get rid of the doc build error), and I'd suggest this wording change:

```
.. note::  The release v3.0 ACRN Configurator assigns COM2 (I/O address ``0x2F8``) to the S5 feature.
   A conflict will occur if you assign ``0x2F8`` to another connection.  In our example, we'll
   use COM3 (I/O address ``0x3F8``).


```

2022-07-19 17:25 UTC, dbkinder approved these changes
LGTM, thanks for the update.

2022-07-19 17:25 UTC, merged