Focus change to new VM when added
projectacrn/acrn-hypervisor pull request #7994
Opened 2022-08-16 07:10 UTC by chuangxke

the focus  change to that new VM on the Basic tab when the new VM  added

Tracked-On: #7914
Signed-off-by: Chuang-Ke <chuangx.ke@intel.com>
Reviewed-by: Junjie Mao <junjie.mao@intel.com>

2022-08-16 07:13 UTC, NanlinXie approved these changes

2022-08-16 07:34 UTC, junjiemao1 requested changes

2022-08-16 07:34 UTC, junjiemao1 commented on misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
> +     this.switchTab(maxVMID)
Please be careful about code indentation.

2022-08-16 09:26 UTC, szhen11 commented
start to run premerge test

2022-08-17 01:32 UTC, szhen11 commented
start to run premerge test

2022-08-17 02:04 UTC, merged