config-tools: modified requirements.txt and update GSG
projectacrn/acrn-hypervisor pull request #8017
Opened 2022-08-18 03:50 UTC by zihengL1

Modified misc/config_tools/configurator/requirements.txt
and misc/config_tools/requirements.txt. Updated getting-started.rst
and acrn_configurator_tool.rst.

Tracked-On: #7975
Signed-off-by: zihengL1 <ziheng.li@intel.com>

2022-08-18 05:17 UTC, dbkinder commented
See comments in #8016

2022-08-18 05:18 UTC, dbkinder requested changes

2022-08-18 05:18 UTC, dbkinder commented on doc/tutorials/acrn_configurator_tool.rst
> +      cd ~/acrn-work/acrn-hypervisor/misc/config_tools/configurator
```suggestion
      cd ~/acrn-work/acrn-hypervisor/misc/config_tools
```

2022-08-18 06:19 UTC, dbkinder approved these changes
This will work (not using the requirements.txt in the GSG for now)

2022-08-26 04:39 UTC, NanlinXie approved these changes

2022-08-26 05:12 UTC, merged